### ISSUE TITLE
Not working in new version opf codeigniter 3.0

### ISSUE THREAD

**Issue by mrez-ir** [danmontgomery/codeigniter-bitauth#13]
Does anybody know how to fix bitauth database insert/update problems in CodeIgniter version 3.0?
It is working perfect in version 2.0 but when I use it in version 3.0 I can not activate other user accounts using example`s default admin account. It shows a activation successful message after click on activate button but database user active value not changes and it remains not activated after a page refresh.
There is same problem for user edits.
How should I fix this?

**Comment by bakus999** [comment]
Check the BitAiuth Library file. It's the line "$this->db->trans_start()" that causes the problem just change it to "$this->db->trans_begin()". Reference can be found in the Codeigniter User Guide (Database>transactions)

**Comment by mrez-ir** [comment]
@bakus999 Thank you. It's very strange that I never found this piece of code after reading all CodeIgniter User guide and change logs.
